import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import CheckConstraint, DateTime, Enum, ForeignKey, Sequence, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.question_result import QuestionResult
    from app.models.user import User


class FeedbackStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MUTED = "muted"


class FeedbackTarget(str, enum.Enum):
    QUESTION_RESULT = "question_result"
    MARK_SCHEME = "mark_scheme"


# Numbers the top-level items behind public_ref ("0001a"); replies reuse their parent's number
feedback_ref_seq = Sequence("feedback_ref_seq", metadata=Base.metadata)


class Feedback(Base):
    __tablename__ = "feedback"
    __table_args__ = (
        # Enum columns store member names, so the check compares against those
        CheckConstraint(
            "(target_type = 'QUESTION_RESULT' AND question_result_id IS NOT NULL"
            " AND mark_scheme_version IS NULL)"
            " OR (target_type = 'MARK_SCHEME' AND mark_scheme_version IS NOT NULL"
            " AND question_result_id IS NULL)",
            name="ck_feedback_single_target",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Short human identifier, e.g. "0010a"; generated by the repository, never by the client
    public_ref: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)

    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), index=True, nullable=False
    )

    target_type: Mapped[FeedbackTarget] = mapped_column(
        Enum(FeedbackTarget, name="feedback_target"), nullable=False
    )
    question_result_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("question_results.id"), index=True, nullable=True
    )
    # Schemes may be repo files, so this is a "name@version" string rather than an FK
    mark_scheme_version: Mapped[str | None] = mapped_column(String, index=True, nullable=True)

    # One reply level only; the repository rejects a reply to a reply
    parent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("feedback.id"), index=True, nullable=True
    )

    body: Mapped[str] = mapped_column(Text, nullable=False)
    # e.g. "Teacher of S3 Mathematics"; supplied by the author
    author_context: Mapped[str | None] = mapped_column(String, nullable=True)

    status: Mapped[FeedbackStatus] = mapped_column(
        Enum(FeedbackStatus, name="feedback_status"),
        nullable=False,
        default=FeedbackStatus.PENDING,
    )
    reviewed_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    edited_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    author: Mapped["User"] = relationship("User", foreign_keys=[author_id])
    reviewed_by: Mapped["User | None"] = relationship("User", foreign_keys=[reviewed_by_id])
    question_result: Mapped["QuestionResult | None"] = relationship("QuestionResult")
    parent: Mapped["Feedback | None"] = relationship(
        "Feedback", remote_side=[id], back_populates="replies"
    )
    replies: Mapped[list["Feedback"]] = relationship("Feedback", back_populates="parent")
