import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    Sequence,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


# Numbers the top-level reports behind public_ref ("R0001a"); disputes reuse their target's number
performance_report_ref_seq = Sequence("performance_report_ref_seq", metadata=Base.metadata)


class PerformanceReport(Base):
    """A public, self-reported claim about how a mark scheme performed when someone tested it.

    Reports carry only aggregate counts and free-text context about the tester and method.
    There is deliberately no field for student names, script images, or any other data that
    could identify a student, and none should be added: a report is a claim about the scheme,
    never a vehicle for sharing student work.

    Reports are unmoderated and contestable. Anyone may publish a dispute (a report with
    disputes_id set) against a top-level report on the same scheme version; the two stand
    side by side. Only an admin may delete a report.
    """

    __tablename__ = "performance_reports"
    __table_args__ = (
        CheckConstraint("scripts_tested > 0", name="ck_performance_reports_scripts_tested"),
        CheckConstraint("questions_judged > 0", name="ck_performance_reports_questions_judged"),
        CheckConstraint(
            "correct_decisions >= 0 AND correct_decisions <= questions_judged",
            name="ck_performance_reports_correct_decisions",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Short human identifier, e.g. "R0010a"; generated by the repository, never by the client
    public_ref: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)

    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), index=True, nullable=False
    )

    # Schemes may be repo files, so this is a "name@version" string rather than an FK
    mark_scheme_version: Mapped[str] = mapped_column(String, index=True, nullable=False)

    # One level only; the repository rejects a dispute of a dispute
    disputes_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("performance_reports.id"), index=True, nullable=True
    )

    scripts_tested: Mapped[int] = mapped_column(Integer, nullable=False)
    questions_judged: Mapped[int] = mapped_column(Integer, nullable=False)
    correct_decisions: Mapped[int] = mapped_column(Integer, nullable=False)

    # e.g. "UNEB S4 Mathematics"
    paper_type: Mapped[str] = mapped_column(String, nullable=False)
    # e.g. "S4"
    level: Mapped[str | None] = mapped_column(String, nullable=True)
    # e.g. "Teacher, 12 years"; supplied by the author
    tester_context: Mapped[str | None] = mapped_column(String, nullable=True)
    # How the tester decided whether each of the scheme's decisions was correct
    method_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Whether the scheme's own author wrote this; set by the repository, never by the client
    is_author_self_report: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    author: Mapped["User"] = relationship("User")
    disputes: Mapped["PerformanceReport | None"] = relationship(
        "PerformanceReport", remote_side=[id], back_populates="disputed_by"
    )
    disputed_by: Mapped[list["PerformanceReport"]] = relationship(
        "PerformanceReport", back_populates="disputes"
    )

    @property
    def accuracy(self) -> float:
        """Derived, never stored: the share of the scheme's decisions the tester judged correct."""
        return self.correct_decisions / self.questions_judged
