"""add mark_schemes table

Revision ID: 3272d619fbe8
Revises: 4b18209d626e
Create Date: 2026-09-23 11:06:23.937008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3272d619fbe8'
down_revision: Union[str, None] = '4b18209d626e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'GENERATED', 'FEEDBACK_DERIVED', name='mark_scheme_source'), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_mark_schemes_name_version')
    )
    op.create_index(op.f('ix_mark_schemes_owner_id'), 'mark_schemes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mark_schemes_owner_id'), table_name='mark_schemes')
    op.drop_table('mark_schemes')
    # ### end Alembic commands ###
    sa.Enum(name='mark_scheme_source').drop(op.get_bind(), checkfirst=True)
