"""add performance_reports table

Revision ID: 411bd72668b3
Revises: 963b7d8aa44c
Create Date: 2026-09-26 20:28:28.167812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411bd72668b3'
down_revision: Union[str, None] = '963b7d8aa44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Not detected by autogenerate: numbers the top-level public_refs
    op.execute(sa.schema.CreateSequence(sa.Sequence('performance_report_ref_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_ref', sa.String(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('mark_scheme_version', sa.String(), nullable=False),
    sa.Column('disputes_id', sa.UUID(), nullable=True),
    sa.Column('scripts_tested', sa.Integer(), nullable=False),
    sa.Column('questions_judged', sa.Integer(), nullable=False),
    sa.Column('correct_decisions', sa.Integer(), nullable=False),
    sa.Column('paper_type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('tester_context', sa.String(), nullable=True),
    sa.Column('method_notes', sa.Text(), nullable=True),
    sa.Column('is_author_self_report', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('correct_decisions >= 0 AND correct_decisions <= questions_judged', name='ck_performance_reports_correct_decisions'),
    sa.CheckConstraint('questions_judged > 0', name='ck_performance_reports_questions_judged'),
    sa.CheckConstraint('scripts_tested > 0', name='ck_performance_reports_scripts_tested'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disputes_id'], ['performance_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reports_author_id'), 'performance_reports', ['author_id'], unique=False)
    op.create_index(op.f('ix_performance_reports_disputes_id'), 'performance_reports', ['disputes_id'], unique=False)
    op.create_index(op.f('ix_performance_reports_mark_scheme_version'), 'performance_reports', ['mark_scheme_version'], unique=False)
    op.create_index(op.f('ix_performance_reports_public_ref'), 'performance_reports', ['public_ref'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_reports_public_ref'), table_name='performance_reports')
    op.drop_index(op.f('ix_performance_reports_mark_scheme_version'), table_name='performance_reports')
    op.drop_index(op.f('ix_performance_reports_disputes_id'), table_name='performance_reports')
    op.drop_index(op.f('ix_performance_reports_author_id'), table_name='performance_reports')
    op.drop_table('performance_reports')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence('performance_report_ref_seq')))
