"""add storage_key to grading_sessions

Revision ID: 4b18209d626e
Revises: 68097ee0a27f
Create Date: 2026-09-17 10:32:01.074160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b18209d626e'
down_revision: Union[str, None] = '68097ee0a27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grading_sessions', sa.Column('storage_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grading_sessions', 'storage_key')
    # ### end Alembic commands ###
