"""add question_papers and link grading_sessions

Revision ID: 59abacaf25fd
Revises: e5f2b8c9a1d4
Create Date: 2026-09-27 20:58:18.868029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59abacaf25fd'
down_revision: Union[str, None] = 'e5f2b8c9a1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'EXTRACTED', 'FAILED', name='paper_status'), nullable=False),
    sa.Column('ocr_engine', sa.String(), nullable=True),
    sa.Column('ocr_markdown', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_papers_owner_id'), 'question_papers', ['owner_id'], unique=False)
    op.add_column('grading_sessions', sa.Column('question_paper_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_grading_sessions_question_paper_id'), 'grading_sessions', ['question_paper_id'], unique=False)
    op.create_foreign_key('fk_grading_sessions_question_paper_id_question_papers', 'grading_sessions', 'question_papers', ['question_paper_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_grading_sessions_question_paper_id_question_papers', 'grading_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_grading_sessions_question_paper_id'), table_name='grading_sessions')
    op.drop_column('grading_sessions', 'question_paper_id')
    op.drop_index(op.f('ix_question_papers_owner_id'), table_name='question_papers')
    op.drop_table('question_papers')
    # ### end Alembic commands ###
    sa.Enum(name='paper_status').drop(op.get_bind(), checkfirst=True)
