"""add payout_attempts table

Revision ID: 963b7d8aa44c
Revises: f968dd822118
Create Date: 2026-09-25 21:37:24.688029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963b7d8aa44c'
down_revision: Union[str, None] = 'f968dd822118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reward_id', sa.UUID(), nullable=False),
    sa.Column('amount_sats', sa.Integer(), nullable=False),
    sa.Column('lightning_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('blink_status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('attempting', 'success', 'failed', 'pending', 'already_paid')", name='ck_payout_attempts_status'),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_attempts_reward_id'), 'payout_attempts', ['reward_id'], unique=False)
    op.create_index('uq_payout_attempts_one_live_per_reward', 'payout_attempts', ['reward_id'], unique=True, postgresql_where=sa.text("status IN ('attempting', 'pending', 'success', 'already_paid')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payout_attempts_one_live_per_reward', table_name='payout_attempts', postgresql_where=sa.text("status IN ('attempting', 'pending', 'success', 'already_paid')"))
    op.drop_index(op.f('ix_payout_attempts_reward_id'), table_name='payout_attempts')
    op.drop_table('payout_attempts')
    # ### end Alembic commands ###
