"""add feedback table

Revision ID: b3dbbd50094b
Revises: b6c59c51e8c7
Create Date: 2026-09-25 07:52:38.817325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3dbbd50094b'
down_revision: Union[str, None] = 'b6c59c51e8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Not detected by autogenerate: numbers the top-level public_refs
    op.execute(sa.schema.CreateSequence(sa.Sequence('feedback_ref_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_ref', sa.String(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('QUESTION_RESULT', 'MARK_SCHEME', name='feedback_target'), nullable=False),
    sa.Column('question_result_id', sa.UUID(), nullable=True),
    sa.Column('mark_scheme_version', sa.String(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_context', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MUTED', name='feedback_status'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(target_type = 'QUESTION_RESULT' AND question_result_id IS NOT NULL AND mark_scheme_version IS NULL) OR (target_type = 'MARK_SCHEME' AND mark_scheme_version IS NOT NULL AND question_result_id IS NULL)", name='ck_feedback_single_target'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['question_result_id'], ['question_results.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_author_id'), 'feedback', ['author_id'], unique=False)
    op.create_index(op.f('ix_feedback_mark_scheme_version'), 'feedback', ['mark_scheme_version'], unique=False)
    op.create_index(op.f('ix_feedback_parent_id'), 'feedback', ['parent_id'], unique=False)
    op.create_index(op.f('ix_feedback_public_ref'), 'feedback', ['public_ref'], unique=True)
    op.create_index(op.f('ix_feedback_question_result_id'), 'feedback', ['question_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_question_result_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_public_ref'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_parent_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_mark_scheme_version'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_author_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
    sa.Enum(name='feedback_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='feedback_target').drop(op.get_bind(), checkfirst=True)
    op.execute(sa.schema.DropSequence(sa.Sequence('feedback_ref_seq')))
