"""add rewards table

Revision ID: f968dd822118
Revises: b3dbbd50094b
Create Date: 2026-09-25 21:14:39.438931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f968dd822118'
down_revision: Union[str, None] = 'b3dbbd50094b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('amount_sats', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('FEEDBACK', 'MARK_SCHEME', 'SCHEME_IMPROVEMENT', name='reward_reason'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('feedback_id', sa.UUID(), nullable=True),
    sa.Column('mark_scheme_version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OWED', 'PAID', 'CANCELLED', name='reward_status'), nullable=False),
    sa.Column('awarded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.CheckConstraint('amount_sats > 0', name='ck_rewards_amount_positive'),
    sa.ForeignKeyConstraint(['awarded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_id')
    )
    op.create_index(op.f('ix_rewards_recipient_id'), 'rewards', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_recipient_id'), table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
    sa.Enum(name='reward_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='reward_reason').drop(op.get_bind(), checkfirst=True)
